# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8091
  connection-timeout: 5000ms
  servlet:
    context-path: /demo

spring:
  # 环境 dev|test|prod
  profiles:
    active: @profileActive@